OneTBB NUMA support API spec
oneapi-src/oneAPI-spec pull request #238
Opened 2020-09-22 09:28 UTC by ivankochin

This patch contains the oneTBB NUMA support API specification.

@akukanov, @alexey-katranov, @aleksei-fedotov please review if possible.

2020-09-22 14:40 UTC, rscohn2 commented
Ignore the build error. I am in the middle of redoing the publish process.

Is this intended to go into the 1.0 spec?

By the way, I have been looking at how nvidia supports multiple cards and the ability to create threads in specific numa nodes will be useful. You may want to create threads in a subset of the numa nodes (the ones with separate PCI interfaces and GPU cards attached). Your API will support it in a natural way.

2020-09-22 14:57 UTC, alexey-katranov commented
> Is this intended to go into the 1.0 spec?

Yes, we just noticed that we missed this API in the Spec. 

As for additional use cases, we are thinking about other criteria for constraints. I believe we can extend the API with new use cases in future.

2020-09-22 15:10 UTC, rscohn2 commented
Yes. API that generate and accept vectors of numa nodes should be a good fit for other use cases.

2020-09-22 15:13 UTC, aleksei-fedotov requested changes

2020-09-22 15:13 UTC, aleksei-fedotov commented on source/elements/oneTBB/source/task_scheduler/task_arena/task_arena_cls.rst
> +        If ``max_concurrency`` and ``reserved_for_masters`` are
```suggestion
        If ``constraints::max_concurrency`` and ``reserved_for_masters`` are
```
?

2020-09-22 15:13 UTC, aleksei-fedotov commented on source/elements/oneTBB/source/task_scheduler/task_arena/task_arena_cls.rst
> +    If ``constraints.numa_node`` is specified, then all threads that enter the arena are automatically
```suggestion
    If ``constraints::numa_node`` is specified, then all threads that enter the arena are automatically
```
Qualify via double colon?

2020-09-22 15:13 UTC, aleksei-fedotov commented on source/elements/oneTBB/source/task_scheduler/task_arena/task_arena_cls.rst
> +resources.
I think we don't need to clarify too precisely what is happening here. This is the spec. We only need to tell that this is an example of how work can be executed on different NUMA nodes simultaneously.

2020-09-22 16:08 UTC, ivankochin commented on source/elements/oneTBB/source/info_namespace.rst
> +``numa_node_id`` - Represents the certain NUMA node identifier.
I agree with you about "the" article, but I am prefer the following form:

```suggestion
``numa_node_id`` - Represents NUMA node identifier.
```

2020-09-22 16:10 UTC, ivankochin commented on source/elements/oneTBB/source/task_scheduler/task_arena/task_arena_cls.rst
> +    ``reserved_for_masters``.  The amount for reservation cannot exceed the limit.
This formulation was copied from the previous constructor, so I would prefer it to save consistency.

2020-09-23 10:04 UTC, ivankochin commented on source/elements/oneTBB/source/task_scheduler/task_arena/task_arena_cls.rst
> +to the corresponding NUMA node.
```suggestion
The example demonstrates ``task_arena`` NUMA support API. Each constructed task_arena is pinned
to the corresponding NUMA node.
```

2020-09-23 10:17 UTC, ivankochin commented on source/elements/oneTBB/source/task_scheduler/task_arena/task_arena_cls.rst
> +The example demonstrates ``task_arena`` NUMA support API. Each constructed task_arena is pinned
```suggestion
The example demonstrates ``task_arena`` NUMA support API. Each constructed ``task_arena`` is pinned
```

2020-09-23 10:17 UTC, aleksei-fedotov commented on source/elements/oneTBB/source/task_scheduler/task_arena/task_arena_cls.rst
> +The example demonstrates ``task_arena`` NUMA support API. Each constructed task_arena is pinned
```suggestion
The example demonstrates ``task_arena`` NUMA support API. Each constructed ``task_arena`` is pinned
```

2020-09-23 10:18 UTC, aleksei-fedotov approved these changes

2020-09-23 10:21 UTC, ivankochin commented
@rscohn2 , we already reviewed this PR, please, merge this patch is you have no objections.

2020-09-23 12:44 UTC, merged