[oneTBB] Add adaptive mutexes
oneapi-src/oneAPI-spec pull request #354
Opened 2021-08-19 10:17 UTC by pavelkumbrasev

Signed-off-by: pavelkumbrasev <pavel.kumbrasev@intel.com>

2021-08-19 10:19 UTC, pavelkumbrasev commented
@alexey-katranov @ivankochin @alexandraepan

2021-08-19 12:15 UTC, pavelkumbrasev commented on source/elements/oneTBB/source/mutual_exclusion/mutex_cls.rst
> +using adaptive approach: the combination of spinlock and waiting on system primitives.
```suggestion
using an adaptive approach, which is a combination of spinlock and waiting on system primitives.
```

2021-08-19 12:16 UTC, pavelkumbrasev commented on source/elements/oneTBB/source/mutual_exclusion/rw_mutex_cls.rst
> +using adaptive approach: the combination of spinlock and waiting on system primitives.
```suggestion
using an adaptive approach, which is a combination of spinlock and waiting on system primitives.
```

2021-08-20 07:51 UTC, ivankochin commented
LGTM!

2021-08-23 06:34 UTC, pavelkumbrasev commented on source/elements/oneTBB/source/mutual_exclusion/mutex_cls.rst
> +using an adaptive approach, which is a combination of spinlock and waiting on system primitives.
```suggestion
using an adaptive approach, it guarantees: that the thread that can't acquire the lock spins before blocking.
```

2021-08-23 06:34 UTC, pavelkumbrasev commented on source/elements/oneTBB/source/mutual_exclusion/rw_mutex_cls.rst
> +using an adaptive approach, which is a combination of spinlock and waiting on system primitives.
```suggestion
using an adaptive approach, it guarantees: that the thread that can't acquire the lock spins before blocking.
```

2021-08-23 06:43 UTC, alexandraepan commented on source/elements/oneTBB/source/mutual_exclusion/mutex_cls.rst
> +using an adaptive approach, it guarantees: that the thread that can't acquire the lock spins before blocking.
```suggestion
using an adaptive approach, it guarantees that the thread that cannot acquire the lock spins before blocking.
```

2021-08-23 06:43 UTC, alexandraepan commented on source/elements/oneTBB/source/mutual_exclusion/mutex_cls.rst
> +    Acquires a lock. It uses adaptive logic for waiting, thus it is blocked after a certain time of busy waiting.
```suggestion
    Acquires a lock. It uses an adaptive logic for waiting, thus it is blocked after a certain time of busy waiting.
```

2021-08-23 06:43 UTC, alexandraepan commented on source/elements/oneTBB/source/mutual_exclusion/rw_mutex_cls.rst
> +using an adaptive approach, it guarantees: that the thread that can't acquire the lock spins before blocking.
```suggestion
using an adaptive approach, it guarantees that the thread that cannot acquire the lock spins before blocking.
```

2021-08-23 06:56 UTC, alexandraepan approved these changes

2021-09-01 10:06 UTC, alexey-katranov approved these changes

2021-09-09 09:11 UTC, kboyarinov requested changes

2021-09-09 09:11 UTC, kboyarinov commented on source/elements/oneTBB/source/mutual_exclusion/mutex_cls.rst
> +.. SPDX-FileCopyrightText: 2020-2021 Intel Corporation
```suggestion
.. SPDX-FileCopyrightText: 2021 Intel Corporation
```

2021-09-09 09:11 UTC, kboyarinov commented on source/elements/oneTBB/source/mutual_exclusion/rw_mutex_cls.rst
> +.. SPDX-FileCopyrightText: 2020-2021 Intel Corporation
```suggestion
.. SPDX-FileCopyrightText: 2021 Intel Corporation
```

2021-09-09 09:14 UTC, kboyarinov approved these changes

2021-09-09 11:46 UTC, merged